var classes = [
    {
        "name": "App\\Action\\AssignManagement",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bookInput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "myEcho",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getblock",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Slim\\Container",
            "Slim\\Http\\Request",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert"
        ],
        "parents": [],
        "lcom": 2,
        "length": 88,
        "vocabulary": 30,
        "volume": 431.81,
        "difficulty": 8.63,
        "effort": 3724.33,
        "level": 0.12,
        "bugs": 0.14,
        "time": 207,
        "intelligentContent": 50.06,
        "number_operators": 19,
        "number_operands": 69,
        "number_operators_unique": 6,
        "number_operands_unique": 24,
        "cloc": 13,
        "loc": 57,
        "lloc": 44,
        "mi": 78.87,
        "mIwoC": 45.16,
        "commentWeight": 33.71,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.46,
        "relativeSystemComplexity": 25.46,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 1.83,
        "totalSystemComplexity": 101.83,
        "package": "App\\Action\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Action\\BlurrdBookTitleSearch",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "booklookinput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "booklook",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bookTitleSearchStart",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 6,
        "ccnMethodMax": 4,
        "externals": [
            "Slim\\Http\\Request"
        ],
        "parents": [],
        "lcom": 2,
        "length": 73,
        "vocabulary": 26,
        "volume": 343.13,
        "difficulty": 6.67,
        "effort": 2287.55,
        "level": 0.15,
        "bugs": 0.11,
        "time": 127,
        "intelligentContent": 51.47,
        "number_operators": 17,
        "number_operands": 56,
        "number_operators_unique": 5,
        "number_operands_unique": 21,
        "cloc": 14,
        "loc": 60,
        "lloc": 46,
        "mi": 79.19,
        "mIwoC": 45.17,
        "commentWeight": 34.02,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 25.25,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 101,
        "package": "App\\Action\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Action\\BlurredCustomerSearch",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "customerSearch",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBlock",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Slim\\Http\\Request",
            "Webmozart\\Assert\\Assert"
        ],
        "parents": [],
        "lcom": 1,
        "length": 49,
        "vocabulary": 18,
        "volume": 204.33,
        "difficulty": 7.31,
        "effort": 1493.15,
        "level": 0.14,
        "bugs": 0.07,
        "time": 83,
        "intelligentContent": 27.96,
        "number_operators": 11,
        "number_operands": 38,
        "number_operators_unique": 5,
        "number_operands_unique": 13,
        "cloc": 9,
        "loc": 40,
        "lloc": 31,
        "mi": 84.41,
        "mIwoC": 50.89,
        "commentWeight": 33.52,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.6,
        "relativeSystemComplexity": 16.6,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 1.8,
        "totalSystemComplexity": 49.8,
        "package": "App\\Action\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Action\\BookDataInput",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bookDataInput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBlock",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Slim\\Http\\Request",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert",
            "Webmozart\\Assert\\Assert"
        ],
        "parents": [],
        "lcom": 1,
        "length": 47,
        "vocabulary": 21,
        "volume": 206.44,
        "difficulty": 5.47,
        "effort": 1128.96,
        "level": 0.18,
        "bugs": 0.07,
        "time": 63,
        "intelligentContent": 37.75,
        "number_operators": 12,
        "number_operands": 35,
        "number_operators_unique": 5,
        "number_operands_unique": 16,
        "cloc": 9,
        "loc": 41,
        "lloc": 32,
        "mi": 83.74,
        "mIwoC": 50.55,
        "commentWeight": 33.19,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.6,
        "relativeSystemComplexity": 16.6,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 1.8,
        "totalSystemComplexity": 49.8,
        "package": "App\\Action\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Action\\ExistsArticleInStore",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bookInput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bookOutput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "erststart",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "Slim\\Http\\Request"
        ],
        "parents": [],
        "lcom": 1,
        "length": 74,
        "vocabulary": 22,
        "volume": 330,
        "difficulty": 8.24,
        "effort": 2717.63,
        "level": 0.12,
        "bugs": 0.11,
        "time": 151,
        "intelligentContent": 40.07,
        "number_operators": 18,
        "number_operands": 56,
        "number_operators_unique": 5,
        "number_operands_unique": 17,
        "cloc": 9,
        "loc": 59,
        "lloc": 50,
        "mi": 73.07,
        "mIwoC": 44.63,
        "commentWeight": 28.44,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 25.25,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 101,
        "package": "App\\Action\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Action\\KundendatenRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "work",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOutputData",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 21,
        "vocabulary": 6,
        "volume": 54.28,
        "difficulty": 7,
        "effort": 379.99,
        "level": 0.14,
        "bugs": 0.02,
        "time": 21,
        "intelligentContent": 7.75,
        "number_operators": 7,
        "number_operands": 14,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 9,
        "loc": 35,
        "lloc": 26,
        "mi": 92.08,
        "mIwoC": 56.72,
        "commentWeight": 35.36,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.58,
        "relativeSystemComplexity": 9.58,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 1.75,
        "totalSystemComplexity": 28.75,
        "package": "App\\Action\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Error\\CustomErrorHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 37,
        "vocabulary": 18,
        "volume": 154.29,
        "difficulty": 3.57,
        "effort": 551.03,
        "level": 0.28,
        "bugs": 0.05,
        "time": 31,
        "intelligentContent": 43.2,
        "number_operators": 12,
        "number_operands": 25,
        "number_operators_unique": 4,
        "number_operands_unique": 14,
        "cloc": 1,
        "loc": 20,
        "lloc": 19,
        "mi": 73.49,
        "mIwoC": 56.51,
        "commentWeight": 16.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.3,
        "relativeSystemComplexity": 81.3,
        "totalStructuralComplexity": 162,
        "totalDataComplexity": 0.6,
        "totalSystemComplexity": 162.6,
        "package": "App\\Error\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Logger\\OwnLogger",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "write",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [
            "Silalahi\\Slim\\Logger"
        ],
        "parents": [
            "Silalahi\\Slim\\Logger"
        ],
        "lcom": 1,
        "length": 60,
        "vocabulary": 28,
        "volume": 288.44,
        "difficulty": 4.67,
        "effort": 1348.15,
        "level": 0.21,
        "bugs": 0.1,
        "time": 75,
        "intelligentContent": 61.71,
        "number_operators": 17,
        "number_operands": 43,
        "number_operators_unique": 5,
        "number_operands_unique": 23,
        "cloc": 11,
        "loc": 43,
        "lloc": 32,
        "mi": 84.29,
        "mIwoC": 49,
        "commentWeight": 35.29,
        "kanDefect": 0.51,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "App\\Logger\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Mapper\\BookTitleInfo",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "work",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getResponseData",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setParams",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 1,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 31,
        "vocabulary": 13,
        "volume": 114.71,
        "difficulty": 6.56,
        "effort": 752.81,
        "level": 0.15,
        "bugs": 0.04,
        "time": 42,
        "intelligentContent": 17.48,
        "number_operators": 10,
        "number_operands": 21,
        "number_operators_unique": 5,
        "number_operands_unique": 8,
        "cloc": 8,
        "loc": 40,
        "lloc": 32,
        "mi": 84.41,
        "mIwoC": 52.48,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 5.17,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 4.67,
        "totalSystemComplexity": 20.67,
        "package": "App\\Mapper\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Mapper\\IsbnInput",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "inputData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isFlag",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 28,
        "vocabulary": 14,
        "volume": 106.61,
        "difficulty": 3.14,
        "effort": 334.35,
        "level": 0.32,
        "bugs": 0.04,
        "time": 19,
        "intelligentContent": 33.99,
        "number_operators": 5,
        "number_operands": 23,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 9,
        "loc": 33,
        "lloc": 24,
        "mi": 91.61,
        "mIwoC": 55.42,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 2.33,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 7,
        "package": "App\\Mapper\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Mapper\\IsbnRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dataRequest",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRequestData",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 38,
        "vocabulary": 17,
        "volume": 155.32,
        "difficulty": 7.36,
        "effort": 1143.75,
        "level": 0.14,
        "bugs": 0.05,
        "time": 64,
        "intelligentContent": 21.09,
        "number_operators": 11,
        "number_operands": 27,
        "number_operators_unique": 6,
        "number_operands_unique": 11,
        "cloc": 9,
        "loc": 38,
        "lloc": 29,
        "mi": 86.44,
        "mIwoC": 52.22,
        "commentWeight": 34.23,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.89,
        "relativeSystemComplexity": 4.89,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 2.67,
        "totalSystemComplexity": 14.67,
        "package": "App\\Mapper\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Mapper\\MapperBookDataInput",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "work",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isFlag",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 22,
        "vocabulary": 11,
        "volume": 76.11,
        "difficulty": 3.19,
        "effort": 242.59,
        "level": 0.31,
        "bugs": 0.03,
        "time": 13,
        "intelligentContent": 23.88,
        "number_operators": 5,
        "number_operands": 17,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 9,
        "loc": 33,
        "lloc": 24,
        "mi": 92.63,
        "mIwoC": 56.45,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 2.33,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 7,
        "package": "App\\Mapper\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Mapper\\MapperCustomerSearch",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "customerDatabaseReq",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDataExport",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 38,
        "vocabulary": 16,
        "volume": 152,
        "difficulty": 9.72,
        "effort": 1477.78,
        "level": 0.1,
        "bugs": 0.05,
        "time": 82,
        "intelligentContent": 15.63,
        "number_operators": 13,
        "number_operands": 25,
        "number_operators_unique": 7,
        "number_operands_unique": 9,
        "cloc": 9,
        "loc": 38,
        "lloc": 29,
        "mi": 86.51,
        "mIwoC": 52.28,
        "commentWeight": 34.23,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.89,
        "relativeSystemComplexity": 4.89,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 2.67,
        "totalSystemComplexity": 14.67,
        "package": "App\\Mapper\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Mapper\\MapperKundendatenRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "work",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getData",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 29,
        "vocabulary": 10,
        "volume": 96.34,
        "difficulty": 4.5,
        "effort": 433.51,
        "level": 0.22,
        "bugs": 0.03,
        "time": 24,
        "intelligentContent": 21.41,
        "number_operators": 8,
        "number_operands": 21,
        "number_operators_unique": 3,
        "number_operands_unique": 7,
        "cloc": 7,
        "loc": 38,
        "lloc": 31,
        "mi": 84.16,
        "mIwoC": 53.31,
        "commentWeight": 30.85,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.33,
        "relativeSystemComplexity": 2.33,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 7,
        "package": "App\\Mapper\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Mapper\\PitchInfo",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "work",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getResponseData",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setParams",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 1,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 23,
        "vocabulary": 9,
        "volume": 72.91,
        "difficulty": 4,
        "effort": 291.63,
        "level": 0.25,
        "bugs": 0.02,
        "time": 16,
        "intelligentContent": 18.23,
        "number_operators": 7,
        "number_operands": 16,
        "number_operators_unique": 3,
        "number_operands_unique": 6,
        "cloc": 13,
        "loc": 42,
        "lloc": 29,
        "mi": 92.74,
        "mIwoC": 54.79,
        "commentWeight": 37.95,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 5.17,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 4.67,
        "totalSystemComplexity": 20.67,
        "package": "App\\Mapper\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Middleware\\CheckLogin",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkUserPassword",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNavigation",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 13,
        "ccn": 10,
        "ccnMethodMax": 8,
        "externals": [
            "Slim\\Http\\Request",
            "Slim\\Http\\Response"
        ],
        "parents": [],
        "lcom": 1,
        "length": 102,
        "vocabulary": 31,
        "volume": 505.33,
        "difficulty": 16.9,
        "effort": 8542.45,
        "level": 0.06,
        "bugs": 0.17,
        "time": 475,
        "intelligentContent": 29.89,
        "number_operators": 31,
        "number_operands": 71,
        "number_operators_unique": 10,
        "number_operands_unique": 21,
        "cloc": 26,
        "loc": 79,
        "lloc": 53,
        "mi": 80.93,
        "mIwoC": 42.11,
        "commentWeight": 38.81,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.64,
        "relativeSystemComplexity": 36.64,
        "totalStructuralComplexity": 144,
        "totalDataComplexity": 2.57,
        "totalSystemComplexity": 146.57,
        "package": "App\\Middleware\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Model\\BookDataControl",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "work",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isFlag",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 7,
        "volume": 44.92,
        "difficulty": 4.13,
        "effort": 185.29,
        "level": 0.24,
        "bugs": 0.01,
        "time": 10,
        "intelligentContent": 10.89,
        "number_operators": 5,
        "number_operands": 11,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 9,
        "loc": 32,
        "lloc": 23,
        "mi": 95.07,
        "mIwoC": 58.46,
        "commentWeight": 36.61,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.89,
        "relativeSystemComplexity": 4.89,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 2.67,
        "totalSystemComplexity": 14.67,
        "package": "App\\Model\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Model\\CustomerSearchControl",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "work",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDataExport",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 7,
        "volume": 44.92,
        "difficulty": 4.13,
        "effort": 185.29,
        "level": 0.24,
        "bugs": 0.01,
        "time": 10,
        "intelligentContent": 10.89,
        "number_operators": 5,
        "number_operands": 11,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 9,
        "loc": 32,
        "lloc": 23,
        "mi": 95.07,
        "mIwoC": 58.46,
        "commentWeight": 36.61,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.89,
        "relativeSystemComplexity": 4.89,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 2.67,
        "totalSystemComplexity": 14.67,
        "package": "App\\Model\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Model\\FindArticle",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRequestParams",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "work",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getArticleData",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 1,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 21,
        "vocabulary": 7,
        "volume": 58.95,
        "difficulty": 5.25,
        "effort": 309.51,
        "level": 0.19,
        "bugs": 0.02,
        "time": 17,
        "intelligentContent": 11.23,
        "number_operators": 7,
        "number_operands": 14,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 12,
        "loc": 41,
        "lloc": 29,
        "mi": 92.6,
        "mIwoC": 55.43,
        "commentWeight": 37.17,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.88,
        "relativeSystemComplexity": 9.88,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 39.5,
        "package": "App\\Model\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Model\\FindBookTitle",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRequestParams",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "work",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTitleData",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 1,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 21,
        "vocabulary": 7,
        "volume": 58.95,
        "difficulty": 5.25,
        "effort": 309.51,
        "level": 0.19,
        "bugs": 0.02,
        "time": 17,
        "intelligentContent": 11.23,
        "number_operators": 7,
        "number_operands": 14,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 8,
        "loc": 37,
        "lloc": 29,
        "mi": 88.42,
        "mIwoC": 55.43,
        "commentWeight": 32.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.88,
        "relativeSystemComplexity": 9.88,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 39.5,
        "package": "App\\Model\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Model\\ModelKundendatenRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "work",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOutputData",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 17,
        "vocabulary": 6,
        "volume": 43.94,
        "difficulty": 5.5,
        "effort": 241.69,
        "level": 0.18,
        "bugs": 0.01,
        "time": 13,
        "intelligentContent": 7.99,
        "number_operators": 6,
        "number_operands": 11,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 9,
        "loc": 35,
        "lloc": 26,
        "mi": 92.72,
        "mIwoC": 57.36,
        "commentWeight": 35.36,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.78,
        "relativeSystemComplexity": 4.78,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 2.33,
        "totalSystemComplexity": 14.33,
        "package": "App\\Model\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Model\\SteuerungApplikation",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "work",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRequestData",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFlag",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 29,
        "vocabulary": 10,
        "volume": 96.34,
        "difficulty": 9.5,
        "effort": 915.19,
        "level": 0.11,
        "bugs": 0.03,
        "time": 51,
        "intelligentContent": 10.14,
        "number_operators": 10,
        "number_operands": 19,
        "number_operators_unique": 5,
        "number_operands_unique": 5,
        "cloc": 13,
        "loc": 46,
        "lloc": 33,
        "mi": 89.26,
        "mIwoC": 52.58,
        "commentWeight": 36.68,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.7,
        "relativeSystemComplexity": 16.7,
        "totalStructuralComplexity": 64,
        "totalDataComplexity": 2.8,
        "totalSystemComplexity": 66.8,
        "package": "App\\Model\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Tool\\GenerateResponse",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "convertToHtml",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "convertToJson",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "htmlWithTwig",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 2,
        "length": 33,
        "vocabulary": 15,
        "volume": 128.93,
        "difficulty": 1.92,
        "effort": 247.94,
        "level": 0.52,
        "bugs": 0.04,
        "time": 14,
        "intelligentContent": 67.04,
        "number_operators": 8,
        "number_operands": 25,
        "number_operators_unique": 2,
        "number_operands_unique": 13,
        "cloc": 16,
        "loc": 36,
        "lloc": 20,
        "mi": 99.64,
        "mIwoC": 56.71,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.28,
        "relativeSystemComplexity": 25.28,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 0.83,
        "totalSystemComplexity": 75.83,
        "package": "App\\Tool\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Tool\\XmlConvert",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "convert",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 5,
        "volume": 34.83,
        "difficulty": 7.5,
        "effort": 261.22,
        "level": 0.13,
        "bugs": 0.01,
        "time": 15,
        "intelligentContent": 4.64,
        "number_operators": 5,
        "number_operands": 10,
        "number_operators_unique": 3,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 15,
        "lloc": 15,
        "mi": 63.28,
        "mIwoC": 63.28,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "App\\Tool\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    }
]