<div class="container">
    <div class="row">
        <div class="col-md-4">
            <form action="{$eintragenUrl}" method="POST">
                <div class="form-group">
                    <label>Email Addresse : </label>
                    <input type="email" name="mail" class="form-control" id="mail" aria-describedby="emailHelp" placeholder="Mailadresse">
                </div>
                <div class="form-group">
                    <label>Information : </label>
                    <input type="text" name="message" class="form-control" id="message" placeholder="Information">
                </div>
                <button type="submit" class="btn btn-primary">eintragen</button>
            </form>
        </div>
        <div class="col-md-8">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>Mail</th>
                        <th>Information</th>
                        <th>Datum</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for value in passedArray %}
                    <tr>
                        <td>{{value.mail}}</td>
                        <td>{{value.message}}</td>
                        <td>{{value.date}}</td>
                    </tr>
                    {% endfor %}


                    </tbody>
                </table>
            </div>


        </div>
    </div>
</div>

