<!-- Formular -->
<div class="col-md-6">
    <form action="{$basisUrl}/buchTitelSuche" method="POST">
        <div class="form-group">
            <label>Buchtitel : </label>
            <input type="text" class="form-control" name="titel" id="titel" placeholder="Titel des Buches eintragen" >
        </div>
        <button type="submit" class="btn btn-primary">Buchsuche</button>
    </form>
</div>
<!-- Bloecke -->
<div class="col-md-6">

    <!-- nicht gefunden -->
    {block1 $block1}
    <div class="col-md-12">
        Buch nicht gefunden
    </div>
    {/block1 $block1}

    <!-- gefunden -->
    {block2 $block2}
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th>ISBN</th>
                    <th>Titel</th>
                    <th>Anzahl vorrätig</th>
                </tr>
                </thead>
                <tbody>
                {foreach $articleData as $key => $value}
                <tr>
                    <td>{$value['ISBN']}</td>
                    <td>{$value['title']}</td>
                    <td>{$value['anzahl']}</td>
                </tr>
                {/foreach}
                </tbody>
            </table>
        </div>
    </div>
    {/block2 $block2}
</div>