<div class ="container">
    <div class="row">
        <div class="col-sm-6">
            <form action="localhost/praktikum/warenwirtschaft/public/eingeben" method="POST">
                <div class="form-inline">
                    <label>ISBN : </label>
                    <input type="text" name="isbn" class="m-5 form-control" id="inlineFormInputName2" placeholder="ISBN" required pattern="[0-9]{10,13}">
                </div>
                <div class="form-inline">
                    <label>Bereich : </label>
                    <select class="m-2 form-control" name="bereich" id="exampleFormControlSelect1">
                        {% for i in range(1, 4) %}
                        <option>{{i}}</option>
                        {% endfor %}
                    </select>
                    <label>Box : </label>
                    <select class="m-2 form-control" name="box" id="exampleFormControlSelect1">
                        {% for i in range(1, 30) %}
                        <option>{{i}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-inline">
                    <label>Zustand des Buches : </label>
                    <select class="m-2 form-control" name="zustand" id="exampleFormControlSelect1">
                        <option>gut</option>
                        <option>genuegend</option>
                        <option>schlecht</option>
                    </select>
                    <button type="submit" class="m-5 btn btn-primary">Abschicken</button>
                </div>
            </form>
        </div>


        <div class="col-sm-6">
            <!-- Titel bekannt -->
            {block1 $block1}
            <div class="col-lg-6" style="height: 500px"><p>Das Buch: {$bookData[0]['title']} wurde in den Bestand aufgenommen</p></div>
            {/block1 $block1}
            <!-- wenn Titel unbekannt -->
            {block2 $block2}
            <div class="col-lg-offset-6 col-lg-6">
                <form action="{basisUrl}/einpflegen" method="POST">
                    <div class="form-inline">
                        <label  class="ml-4 mr-sm-2">ISBN : </label><input name="isbn" type="text" class="m-2 form-control mb-2 mr-sm-2" id="inlineFormInputName2" style="width: 150px" placeholder="ISBN">
                        <label  class="ml-4 mr-sm-2">Titel : </label><input name="title" type="text" class="m-2 form-control mb-2 mr-sm-2" id="inlineFormInputName2" style="width: 150px" placeholder="Titel">
                    </div>
                    <div class="form-inline">
                        <label  class="ml-3 mr-sm-2">Verlag : </label><input name="verlag" type="text" class="m-2 form-control mb-2 mr-sm-2" id="inlineFormInputName2" style="width: 150px" placeholder="Verlag">
                        <button type="submit" class="ml-4 btn btn-primary">Hinzufügen</button>
                    </div>
                </form>
            </div>
            {/block2 $block2}
            <!-- Stammdaten Erweiterung erfolgreich -->
            {block3 $block3}
            <div class="col-lg-6" style="height: 500px"><p>Die Stammdaten wurden erweitert</p></div>
            {/block3 $block3}
        </div>
    </div>
</div>
