<div class="container">
    <div class="row">
        <div class="col-sm-6 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Mockaroo Export</h4>
                </div>
                <div class="card-body">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Vorn.</th>
                                <th scope="col">Nachn.</th>
                                <th scope="col">email</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in mockarooOutputData %}
                            <tr>
                                <td>{{item.id}}</td>
                                <td>{{item.first_name}}</td>
                                <td>{{item.last_name}}</td>
                                <td>{{item.email}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">

                </div>
            </div>
        </div>
    </div>
</div>

