<!-- Formular -->
<div class="col-md-12">
    <div class="card">

        <div class="card-header">
            <h4>Suche nach Buchtitel</h4>
        </div>

        <div class="card-body">
            <form action="{{basisUrl}}/buchTitelSuche" method="POST">
                <div class="form-group">
                    <label>&nbsp </label>
                    <input type="text" class="form-control" name="titel" id="titel" placeholder="Titel des Buches eintragen" >
                </div>
                <button type="submit" class="btn btn-primary">Suchen</button>
            </form>
        </div>
        <div class="card-footer" style="background-color: #4e73df">&nbsp</div>
    </div>
</div>
<!-- Bloecke -->
<div class="col-md-12">

    <!-- nicht gefunden -->
    {% if block1 %}
    <div class="card">

        <div class="card-header">
            <h4 class="card-title">Lagerbestand</h4>
            <h5 class="card-subtitle">&nbsp</h5>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                Buch nicht gefunden
            </div>
        </div>

        <div class="card-footer" style="background-color: #4e73df"></div>
    </div>
    {% endif %}

    <!-- gefunden -->
    {% if block2 %}
    <div class="card">

        <div class="card-header">
            <h4 class="card-title">Lagerbestand</h4>
            <h5 class="card-subtitle">&nbsp</h5>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>ISBN</th>
                            <th>Titel</th>
                            <th>Anzahl vorrätig</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for article in articleData %}
                        <tr>
                            <td>{{article.ISBN}}</td>
                            <td>{{article.title}}</td>
                            <td>{{article.anzahl}}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="card-footer" style="background-color: #4e73df">
            &nbsp;
        </div>
    </div>
    {% endif %}
</div>
