<div class ="container ">
    <div class="row">
        <div class="col-sm-6 mx-auto">
            <div class="card ">
                <div class="card-header">
                    <h4 class="card-title">{{ModulName}}</h4>
                </div>
                <div class="card-body">
                    <form action="{{basisUrl}}/kundensuche" method="POST">
                        <div class="form-inline">
                            <input type="text" name="last_name" class="m-2 form-control" id="inlineFormInputName2" placeholder="Nachname" required pattern="[a-zA-Z]{3,50}">
                            <button type="submit" class="m-2 btn btn-primary">Abschicken</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    &nbsp;
                </div>
            </div>
        </div>


        {% if block1 %}
        <div class="col-sm-auto mb-4 mx-auto">
            <!-- Kunde unbekannt -->
            <div class="card">
                <div class="card-header bg-danger">
                    <h4>Fehlgeschlagen</h4>
                </div>
                <div class="card-body">
                    <div class="col-lg-6" style="height: 500px"><p>Es wurden keine Übereinstimmungen gefunden</p></div>
                </div>
                <div class="card-footer bg-danger">
                    &nbsp;
                </div>
            </div>
        </div>
        {% endif %}

        {% if block2 %}
        <div class="col-sm-auto mt-4 mb-4 mx-auto">
            <!-- Datensätze gefunden -->
            <div class="card">
                <div class="card-header bg-success">
                    <h4>Erfolgreich</h4>
                </div>
                <div class="card-body mx-auto">

                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Vorn.</th>
                            <th scope="col">Nachn.</th>
                            <th scope="col">email</th>
                            <th scope="col">Straße</th>
                            <th scope="col">Hausr.</th>
                            <th scope="col">Plz</th>
                            <th scope="col">Stadt</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if flag == true %}
                        {% for item in export %}
                        <tr>
                            <td>{{item.id}}</td>
                            <td>{{item.first_name}}</td>
                            <td>{{item.last_name}}</td>
                            <td>{{item.email}}</td>
                            <td>{{item.street_name}}</td>
                            <td>{{item.street_number}}</td>
                            <td>{{item.postal_code}}</td>
                            <td>{{item.city}}</td>
                        </tr>
                        {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                </div>

                <div class="card-footer bg-success">
                    &nbsp;
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
