<div class ="container">
    <div class="row">
        <div class="col-sm-6">
            <form action="{basisUrl}/kundensuche" method="POST">
                <div class="form-inline">
                    <input type="text" name="last_name" class="m-2 form-control" id="inlineFormInputName2" placeholder="Nachname" required pattern="[a-zA-Z]{3,50}">
                    <button type="submit" class="m-2 btn btn-primary">Abschicken</button>
                </div>
            </form>
        </div>



        <div class="col-sm-6">
            <!-- Kunde unbekannt -->
            {block1 $block1}
                <div class="col-lg-6" style="height: 500px"><p>Keine Datensätze gefunden</p></div>
            {/block1 $block1}
        </div>
        <div class="col-sm-6">
            <!-- Datensätze gefunden -->
            {block2 $block2}
            <div class="col-lg-offset-6 col-lg-6">
                <table class="table table-dark">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Vorn.</th>
                        <th scope="col">Nachn.</th>
                        <th scope="col">email</th>
                        <th scope="col">Straße</th>
                        <th scope="col">Hausr.</th>
                        <th scope="col">Plz</th>
                        <th scope="col">Stadt</th>
                    </tr>
                    </thead>
                    <tbody>
                    {if $databaseExport['flag'] == true}
                        {foreach $databaseExport['export'] as $key => $value}
                        <tr>
                            <td>{$value['id']}</td>
                            <td>{$value['first_name']}</td>
                            <td>{$value['last_name']}</td>
                            <td>{$value['email']}</td>
                            <td>{$value['street_name']}</td>
                            <td>{$value['street_number']}</td>
                            <td>{$value['postal_code']}</td>
                            <td>{$value['city']}</td>
                        </tr>
                        {/foreach}
                    {/if}
                    </tbody>
                </table>
            </div>
            {/block2 $block2}
        </div>
    </div>
</div>
