<!DOCTYPE html>
<html lang="en">
<head>
    <title>Warenwirtschaft</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
                <link rel="stylesheet" type="text/css" href="{{basisUrl}}/css/warenwirtschaft.css">
                </head>
                <body>
                <div class="container-fluid">
                    <div class="row d-none d-md-block">
                        <div class="col-md-12 rot bg-danger">Kopf</div>
                    </div>

                    <div class="row-md-12">
                        <!-- Navigation -->
                        <div class="col-md-2 gruen d-none d-md-block bg-danger rand_rot">
                            <a href='{{basisUrl}}/erststartArtikelSuche'><button type="button" class="btn btn-success">Auslagern</button></a><br>
                            <a href='{{basisUrl}}/eingabemaske'><button type="button" class="btn btn-success">Einlagern</button></a><br>
                            <a href='{{basisUrl}}/kundensucheErststart'><button type="button" class="btn btn-success">Kundensuche</button></a><br>
                            <a href='{{basisUrl}}/buchTitelSucheStart'><button type="button" class="btn btn-success">Buchtitelsuche</button></a><br>
                        </div>
                        <!-- Content -->
                        <div class="col-md-10 rand_rot">{{include('content.phtml')}}</div>
                    </div>

                    <div class="row d-none d-md-block">
                        <div class="col-md-12 rot bg-danger">Fuss</div>
                    </div>
                </div>
            </div>
        </body>
        </html>
