<!-- Bootstrap 4 Tutorial von www.bootstrapworld.de -->
<!-- ============================================== -->
<html lang="de">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS laden -->
    <link rel="stylesheet" href="source/bootstrap-4.0.0/css/bootstrap.min.css" />

    <!-- eigene CSS - Datei -->
    <link rel="stylesheet" href="css/projekt.css" />

</head>
<body>

<!-- HIER bitte deinen HTML-Code einfuegen -->
<div class="container bg-dark" >
    <nav class="navbar navbar-expand-lg navbar-light bg-faded ">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand text-light" href="#">WarenwirtschaftNG</a>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link text-light" href="#">Einlagern</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="#">Kundensuche</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="#">Platzhalter</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="row">
        <div class="col-md-12 col-12 border_green bg-dark text-light">
            <span class="navbar-text">
                &copy; WarenwirtschaftNG
            </span>
        </div>
    </div>
</div>

<script src="source/jquery-3.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="source/bootstrap-4.0.0/js/bootstrap.min.js"></script>
</body>
</html>