<div class="container">
    <div class="row">
        <div class="card">
            <div class="card-header">
                <h4>Login</h4>
            </div>
            <div class="card-body">
                <form action="{{basisUrl}}" method="POST">
                    <input type="text" name="user" class="m-2 form-control" id="loginname" placeholder="Username">
                    <input type="text" name="password" class="m-2 form-control" id="password" placeholder="Password">
                    <button type="submit" class="m-2 btn btn-primary">Abschicken</button>
                </form>
            </div>
            <div class="card-footer">

            </div>
        </div>
    </div>
</div>

