<!-- Formular -->
<div class="col-md-10">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Suche nach ISBN</h4>
        </div>
        <div class="card-body">
            <form action="{{basisUrl}}/abrufen" method="POST">
                <div class="form-group">
                    <label>&nbsp </label>
                    <input type="text" class="form-control" name="isbn" id="isbn" placeholder="z.B.: 9783411720156" required >
                </div>
                <button type="submit" class="btn btn-primary">abfragen Lagerbestand</button>
            </form>
        </div>
        <div class="card-footer">&nbsp</div>
    </div>
</div>
<!-- Bloecke -->
<div class="col-md-10">

    <!-- nicht gefunden -->

    {% if block1 %}
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Lagerbestand</h4>
            <h5 class="card-subtitle">&nbsp</h5>
        </div>
        <div class="card-body">
            <div class="col-md-12">
                Artikel nicht gefunden
            </div>
        </div>
        <div class="card-footer" style="background-color: #4e73df">&nbsp</div>
    </div>
    {% endif %}

    <!-- gefunden -->
    {% if block2 %}
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Lagerbestand</h4>
        </div>
        <div class="card-body">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Bereich</th>
                            <th>Box</th>
                            <th>Titel</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for article in articleData %}
                        <tr>
                            <td>{{article.bereich}}</td>
                            <td>{{article.box}}</td>
                            <td>{{article.title}}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="card-footer" style="background-color: #4e73df">&nbsp</div>
    </div>
    {% endif %}
</div>